### ISSUE TITLE
Add docs for ubuntu dependencies

### ISSUE THREAD

**Issue by johannes-graeter** [glato/emerge#15]
**Describe the bug**
When installing from pip3 on ubuntu deps
```bash
apt-get install graphviz graphviz-dev
```
are needed, could you add this to the how to install from pip section of the README?

**Describe your environment**
- ubuntu 20.04
- Python 3.8.10, pip 22.0.3

**Comment by glato** [comment]
@johannes-graeter Confirmed, thanks for reporting this issue. Just as you described, after

```
apt-get install graphviz graphviz-dev
```

everything installed fine also on ubuntu 21.10. Just added this to the README 👍.
