### ISSUE TITLE
Opinionated examples of "good" graphs and "bad" graphs

### ISSUE THREAD

**Issue by johannes-graeter** [glato/emerge#17]
**Is your feature request related to a problem? Please describe.**
I just created the first graph of one of the projects I work in. It looks AMAZING!!! First seeing this graph however it is kind of hard to draw concrete conclusions from it. It would be awesome to have some opinionated examples (f.e. I could imagine nicely seperated clusters like in the firework-like graphs in the README point to good interfaces and well made modules whereas tightly entangled ones smell like a need for interface-lift...) in order to speed up the process of learning to interpret those.

**Describe the solution you'd like**
Would be cool to have some more examples as in the readme that do not only show how it looks like but point to possible interpretations.

**Comment by glato** [comment]
@johannes-graeter Thanks a lot for the feedback 👍. It sounds like a useful addition to the README to add further examples and explain some indicators (that e.g. might reveal an increased modularity or in the opposite an increased necessity to create interfaces/abstractions), which could help derive insights more easily or intuitively. I'll see what I can do about that in the following days 🤔.

**Comment by johannes-graeter** [comment]
Awesome glato, thanks for your great project and your dedication!

**Comment by johannes-graeter** [comment]
@glato This is awesome work, thanks exactly what I had in mind! Already helped me a lot (especially the hint to ignre dependencies)
