### ISSUE TITLE
update click to >8.0.0

### ISSUE THREAD

**Issue by johannes-graeter** [glato/emerge#19]
**Describe the bug**
Emerge uses outdated click version 7. Could you update to >8 to avoid conflicts with other packages?

**Describe your environment**
- Linux 20.04
- python 3.8.10
- pip 22.0.04

**To Reproduce**
1. install f.e. ```pip install dunk```
2. observe conflict message

**Expected behavior**
Install without conflict

**Comment by glato** [comment]
@johannes-graeter Thanks for the feedback, this should be fixed in the current release `1.2.2` (https://github.com/glato/emerge/releases/tag/1.2.2), dependencies should be no longer pinned and reduced to a smaller set.
