### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by tikazyq** [glato/emerge#24]
**Is your feature request related to a problem? Please describe.**
It seems emerge does not support the popular programming language Golang

**Describe the solution you'd like**
Support golang

**Comment by glato** [comment]
@tikazyq Just released version `1.4.0` https://github.com/glato/emerge/releases/tag/1.4.0 which has `experimental` Golang support. Would love any feedback 👋.

**Comment by tikazyq** [comment]
Brilliant! I will definitely take a look!

**Comment by tikazyq** [comment]
> @tikazyq Just released version `1.4.0` https://github.com/glato/emerge/releases/tag/1.4.0 which has `experimental` Golang support. Would love any feedback 👋.

Btw, am I supposed to compile from the source myself? Or is there something that's already handy

**Comment by glato** [comment]
@tikazyq Either you clone and run emerge from source directly or you could simply setup a python virtual environment and install the emerge-viz package. Just check the steps at https://github.com/glato/emerge#how-to-install-and-use-emerge-as-a-user (*How to install and use emerge as a user*).

**Comment by glato** [comment]
Closing this issue, since golang support is implemented now.
