### ISSUE TITLE
Improved ability to exclude dependencies

### ISSUE THREAD

**Issue by and3rson** [glato/emerge#27]
**Is your feature request related to a problem? Please describe.**
It's ~hard~ not possible to exclude built-in Python modules with short names like `os`, `re`, etc using `ignore_dependencies_containing` without implicitly excluding other dependencies. For example, `position` (contains "os") and `create_user` (contains "re") will be unwittingly excluded as well.

**Describe the solution you'd like**
It would be nice to either allow regular or glob-style expressions in `ignore_dependencies_containing` or add a new parameter, such as `ignore_dependencies_matching`.

**Optional: Describe alternatives you've considered**
No alternatives for this as far as I'm aware.

**Optional: Additional context**
I'm new to `emerge`, so please let me know in case I missed anything or if this is actually possible ouf of the box.

**Comment by glato** [comment]
Hi @and3rson Thanks for your feedback and the proposed enhancement. It should be relatively easy to include your proposed config parameter `ignore_dependencies_matching`. I will implement this soon and release a new version. Thanks for your support and the useful suggestion  👍 .

**Comment by and3rson** [comment]
@glato Awesome! I actually did the same in my local version, I can submit a PR for this if you want.

**Comment by glato** [comment]
@and3rson That would be fantastic 🚀.

**Comment by glato** [comment]
@and3rson great, thank you very much 👍 .
