### ISSUE TITLE
JS files got duplicated

### ISSUE THREAD

**Issue by nicoespeon** [glato/emerge#4]
I noticed something while generating graphs for JS projects I'm working with:

![image](https://user-images.githubusercontent.com/1094774/109437576-79a80380-79f3-11eb-95f9-3388b57e480f.png)

These 2 files are the same, but they are imported from 2 distinct files relatively:
![image](https://user-images.githubusercontent.com/1094774/109437639-dd323100-79f3-11eb-879f-23d7c74b8ccc.png)

I think a solution would be to resolve the path of imported files relative to the root of the project. What do you think? Is there a similar problem in other languages or is it specific to the JS parser?

**Comment by glato** [comment]
You're absolutely right, I've already started to migrate the path resolving in this direction. Will try to come up with a more robust path resolving in the following days that works exactly that way.

**Comment by glato** [comment]
@nicoespeon Just pushed the bugfix version 0.14.1, which should hopefully (mostly) fix the duplicate issues by using relative analysis/project paths as a base for file results and parsed dependencies. Need to test and maybe optimize that further in the coming days.

**Comment by nicoespeon** [comment]
Awesome news @glato 👏 

I'll test that this week and get back to you with results.

**Comment by nicoespeon** [comment]
It looks better indeed! But I still find some remaining duplication: 
![image](https://user-images.githubusercontent.com/1094774/110403727-9673b500-804b-11eb-8056-07eae1128c14.png)

The structure is the following:

```
app/
|__ pages/
|   |__ purchase.js  # imports "../components/purchase/detailed-logs" 
|
|__ components/
    |__ purchase/
        |__ simple-logs.js # imports "./detailed-logs" 
        |__ detailed-logs.js
`
``

Somehow, one of them results in `app/components/purchase/detailed-logs.js` and the other in `../components/purchase/detailed-logs`.

Do you need help to debug this one?

**Comment by glato** [comment]
That‘s interesting. I‘ll try to create a unit test based on this setup, to better debug and solve this case. I‘ll get back to you @nicoespeon, thanks for the report 😉

**Comment by glato** [comment]
@nicoespeon Your structure example was very helpful, I've constructed the same and hopefully found the bug. It looks promising so far:

<img width="423" alt="correct_dependency_path_resolving" src="https://user-images.githubusercontent.com/9966438/110528078-02bbea80-8118-11eb-8449-dff3aecca869.png">

I'll test this with more path cases tomorrow and on bigger examples.

**Comment by nicoespeon** [comment]
Glad it was helpful! Improving the parser, one test at a time 🧱 👍

**Comment by glato** [comment]
@nicoespeon I've updated the (dependency) path resolving for TS and JS in the new version 0.15.1. This includes some smaller refactorings that allows to better unit test some path resolving methods. I've tested this with the source repos of Angular and React, seems to be promising so far. Would be great if you find some time to re-test this with version 0.15.1 and report back if this solved the problems?

**Comment by nicoespeon** [comment]
Did another try today and that worked wonderfully!
![image](https://user-images.githubusercontent.com/1094774/111044173-ecae7280-8414-11eb-869d-f5a1e9cc7656.png)

Great job you did here 👏 

I'll experiment around, see if the graph is overall correct (this one is a reasonable-sized project I can grasp with my brain). Then I'll also experiment on a much bigger project I can't grasp.

I'll let you know if I find issues. If I can, I'll attempt to fix them too 👍 
In the meantime, this issue looks fixed to me. Thank you!

**Comment by nicoespeon** [comment]
@glato I just found a file that was a solo-node, floating around. Turns out this is a dead code that's not imported anywhere 💯 

Thank you for this quick win I got here!
