### ISSUE TITLE
Upload emerge 2.0.7 to pip repository

### ISSUE THREAD

**Issue by davidbaena** [glato/emerge#56]
**Is your feature request related to a problem? Please describe.**
The last version of emerge is 2.0.0 from pip, but there is a 2.0.7 with fixes that I want to upgrade

**Describe the solution you'd like**
Upload 2.0.7 version to pip:
https://pypi.org/project/emerge-viz/

Thanks!!

**Comment by glato** [comment]
@davidbaena Thanks for the hint, just updated and released `2.0.7` of emerge also on pypi, now easy to install with `pip install emerge-viz`.
