### ISSUE TITLE
Better if follow file soft link

### ISSUE THREAD

**Issue by shengyang998** [glato/emerge#8]
Use `os.path.realpath` to follow link.
In case the link failed, use `os.path.exists` to check the file is exists.

https://github.com/glato/emerge/blob/ca41795bb8cacf6b240b7ea8cf1d45893e8f515a/emerge/analysis.py#L435-L436

**Comment by glato** [comment]
@shengyang998 sorry it was taking so long and thanks for the hint, the new version 0.18.4 should take care of such symlink issues.
